name: Compole AHK to EXE

on: push

jobs:
  AhkToExe:
    name: AhkToExe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: main.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: example.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
